const canvas=document.getElementById('game');const ctx=canvas.getContext('2d');
const UI=id=>document.getElementById(id);const W=390,H=780,GROUND=650;
let state='menu',paused=false,practice=false,levelIndex=0,last=0,camera=0,attempt=0,checkpoint=0;
let save=JSON.parse(localStorage.getItem('onemore-save')||'{"attempts":0,"gems":0,"best":{},"unlocked":1,"sound":true}');
const levels=[
{name:'FIRST LIGHT',speed:190,length:2600,accent:'#28b6ff',obs:[[520,1],[720,2],[980,1],[1240,3],[1580,2],[1870,1],[2140,3]]},
{name:'HOT WIRE',speed:205,length:3000,accent:'#ff8b18',obs:[[430,2],[700,1],[900,3],[1190,2],[1480,3],[1830,1],[2090,2],[2410,3]]},
{name:'AFTERIMAGE',speed:220,length:3350,accent:'#8f6cff',obs:[[400,1],[610,3],[920,2],[1180,1],[1410,3],[1750,3],[2150,2],[2540,1],[2900,3]]},
{name:'REDLINE',speed:235,length:3700,accent:'#ff3d63',obs:[[380,2],[620,2],[870,3],[1120,1],[1370,3],[1690,2],[2010,3],[2330,1],[2620,3],[3180,2]]},
{name:'NO SIGNAL',speed:250,length:4100,accent:'#35e0a1',obs:[[350,1],[560,3],[810,2],[1030,3],[1340,1],[1560,3],[1880,2],[2220,3],[2580,2],[3000,3],[3510,1]]},
{name:'ONE MORE',speed:265,length:4700,accent:'#ffd34d',obs:[[340,2],[520,3],[760,1],[980,3],[1210,2],[1480,3],[1770,1],[1980,3],[2300,2],[2650,3],[3010,3],[3380,2],[3780,3],[4210,2]]}
];
let p={x:95,y:GROUND-30,w:30,h:30,vy:0,rot:0,onGround:true,alive:true};
function persist(){localStorage.setItem('onemore-save',JSON.stringify(save));updateStats()}
function updateStats(){UI('attemptStat').textContent=save.attempts;UI('gemStat').textContent=save.gems;UI('bestStat').textContent=Math.max(0,...Object.values(save.best||{}))+'%';UI('soundBtn').textContent='SOUND: '+(save.sound?'ON':'OFF')}
function screen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));if(id)UI(id).classList.add('active')}
function toast(t){UI('toast').textContent=t;UI('toast').classList.add('show');setTimeout(()=>UI('toast').classList.remove('show'),1100)}
function reset(fromCheckpoint=false){const L=levels[levelIndex];camera=fromCheckpoint?checkpoint:0;p={x:95,y:GROUND-30,w:30,h:30,vy:0,rot:0,onGround:true,alive:true};attempt++;save.attempts++;persist();UI('attemptHud').textContent=attempt;paused=false;state='playing';screen(null);UI('hud').classList.remove('hidden');tone(240,.03)}
function start(i=levelIndex,isPractice=false){levelIndex=i;practice=isPractice;attempt=0;checkpoint=0;reset(false)}
function jump(){if(state!=='playing'||paused||!p.alive)return;if(p.onGround){p.vy=-500;p.onGround=false;tone(520,.045)}}
function tone(freq,dur){if(!save.sound)return;try{const A=window.AudioContext||window.webkitAudioContext;window._ac=window._ac||new A();const o=_ac.createOscillator(),g=_ac.createGain();o.type='square';o.frequency.value=freq;g.gain.value=.025;o.connect(g);g.connect(_ac.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,_ac.currentTime+dur);o.stop(_ac.currentTime+dur)}catch(e){}}
function obstacleRect(x,type){if(type===1)return{x:x-camera,y:GROUND-34,w:34,h:34,kind:'spike'};if(type===2)return{x:x-camera,y:GROUND-34,w:68,h:34,kind:'spikes'};return{x:x-camera,y:GROUND-78,w:58,h:78,kind:'block'}}
function hit(a,b){const pad=6;return a.x+pad<b.x+b.w-pad&&a.x+a.w-pad>b.x+pad&&a.y+pad<b.y+b.h-pad&&a.y+a.h-pad>b.y+pad}
function die(){if(!p.alive)return;p.alive=false;tone(90,.12);const progress=Math.floor(camera/levels[levelIndex].length*100);save.best[levelIndex]=Math.max(save.best[levelIndex]||0,progress);persist();setTimeout(()=>{if(state==='playing')reset(practice&&checkpoint>0)},330)}
function finish(){state='finish';UI('hud').classList.add('hidden');save.best[levelIndex]=100;save.gems+=10;save.unlocked=Math.max(save.unlocked,Math.min(levels.length,levelIndex+2));persist();tone(760,.18);UI('finishTitle').textContent=levels[levelIndex].name;UI('finishStats').textContent=`100% · +10 GEMS · ${attempt} ATTEMPT${attempt===1?'':'S'}`;UI('nextBtn').style.display=levelIndex<levels.length-1?'block':'none';screen('finishScreen')}
function update(dt){if(state!=='playing'||paused||!p.alive)return;const L=levels[levelIndex];camera+=L.speed*dt;p.vy+=1280*dt;p.y+=p.vy*dt;p.rot+=dt*5.5;if(p.y+p.h>=GROUND){p.y=GROUND-p.h;p.vy=0;p.onGround=true;p.rot=Math.round(p.rot/(Math.PI/2))*(Math.PI/2)}
for(const o of L.obs){const r=obstacleRect(o[0],o[1]);if(r.x>-80&&r.x<W+80&&hit(p,r)){die();break}}
if(practice){const mark=Math.floor(camera/700)*700;if(mark>checkpoint&&mark<L.length-500){checkpoint=mark;toast('CHECKPOINT')}}
if(camera>=L.length)finish();const pct=Math.min(100,Math.floor(camera/L.length*100));UI('progressHud').textContent=pct+'%';UI('progressBar').style.width=pct+'%'}
function drawBg(L,t){ctx.fillStyle='#030811';ctx.fillRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#071426');g.addColorStop(1,'#02050a');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.13;for(let i=0;i<8;i++){const x=(i*77-(camera*.08)%77);ctx.fillStyle=i%2?L.accent:'#28b6ff';ctx.fillRect(x,150,1,430)}ctx.globalAlpha=1;for(let i=0;i<24;i++){const x=(i*97-(camera*.2)%97);const y=220+(i*53)%330;ctx.fillStyle=i%3? '#15314d':L.accent;ctx.fillRect(x,y,3,3)}}
function spike(x,y,w,h){ctx.beginPath();ctx.moveTo(x,y+h);ctx.lineTo(x+w/2,y);ctx.lineTo(x+w,y+h);ctx.closePath();ctx.fillStyle='#f7fbff';ctx.shadowBlur=12;ctx.shadowColor='#9edcff';ctx.fill();ctx.shadowBlur=0}
function draw(){const L=levels[levelIndex]||levels[0];drawBg(L,performance.now());ctx.strokeStyle='#aee7ff';ctx.lineWidth=3;ctx.shadowBlur=12;ctx.shadowColor='#28b6ff';ctx.beginPath();ctx.moveTo(0,GROUND);ctx.lineTo(W,GROUND);ctx.stroke();ctx.shadowBlur=0;if(state==='playing'||state==='finish'){for(const o of L.obs){const r=obstacleRect(o[0],o[1]);if(r.x<-100||r.x>W+100)continue;if(r.kind==='spike')spike(r.x,r.y,r.w,r.h);else if(r.kind==='spikes'){spike(r.x,r.y,34,34);spike(r.x+34,r.y,34,34)}else{ctx.strokeStyle='#f5fbff';ctx.lineWidth=3;ctx.shadowBlur=10;ctx.shadowColor=L.accent;ctx.strokeRect(r.x,r.y,r.w,r.h);ctx.fillStyle='#08121e';ctx.fillRect(r.x+3,r.y+3,r.w-6,r.h-6);ctx.fillStyle=L.accent;ctx.fillRect(r.x,r.y,58,5);ctx.shadowBlur=0}}ctx.save();ctx.translate(p.x+p.w/2,p.y+p.h/2);ctx.rotate(p.rot);ctx.fillStyle='#fff';ctx.shadowBlur=16;ctx.shadowColor='#33bfff';ctx.fillRect(-15,-15,30,30);ctx.fillStyle=L.accent;ctx.fillRect(-6,-6,12,12);ctx.shadowBlur=0;ctx.restore();if(practice&&checkpoint){const cx=checkpoint-camera+95;ctx.strokeStyle='#ff8b18';ctx.setLineDash([4,5]);ctx.beginPath();ctx.moveTo(cx,220);ctx.lineTo(cx,GROUND);ctx.stroke();ctx.setLineDash([])}}}
function loop(ts){const dt=Math.min(.032,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function buildLevels(){const g=UI('levelGrid');g.innerHTML='';levels.forEach((L,i)=>{const b=document.createElement('button');b.className='level-card';b.disabled=i>=save.unlocked;b.innerHTML=`<b>${String(i+1).padStart(2,'0')} · ${L.name}</b><small>${i<save.unlocked?(save.best[i]||0)+'% BEST':'LOCKED'}</small>`;b.onclick=()=>start(i,false);g.appendChild(b)})}
UI('playBtn').onclick=()=>start(Math.min(save.unlocked-1,levels.length-1),false);UI('practiceBtn').onclick=()=>start(Math.min(save.unlocked-1,levels.length-1),true);UI('levelsBtn').onclick=()=>{buildLevels();screen('levelScreen')};document.querySelector('[data-back]').onclick=()=>screen('menu');UI('soundBtn').onclick=()=>{save.sound=!save.sound;persist()};UI('pauseBtn').onclick=()=>{paused=true;screen('pauseScreen')};UI('resumeBtn').onclick=()=>{paused=false;screen(null)};UI('restartBtn').onclick=()=>reset(false);UI('menuBtn').onclick=()=>{state='menu';UI('hud').classList.add('hidden');screen('menu')};UI('finishMenuBtn').onclick=UI('menuBtn').onclick;UI('replayBtn').onclick=()=>start(levelIndex,practice);UI('nextBtn').onclick=()=>start(Math.min(levelIndex+1,levels.length-1),false);
canvas.addEventListener('pointerdown',jump);document.addEventListener('keydown',e=>{if(['Space','ArrowUp'].includes(e.code)){e.preventDefault();jump()}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing'){paused=true;screen('pauseScreen')}});updateStats();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
